In [1]:
import numpy as np

In [31]:
x = np.array([5, 10, 15, 20, 25, 30, 35])
x_copy=x.copy()

print(x[1])  # Indexing
print(x[1:6]) # Slicing
print(x[1:6:3]) # Slicing with step
print(len(x))#length of array

10
[10 15 20 25 30]
[10 25]
7


In [32]:
x[2]=13#updating np array
print(x)


[ 5 10 13 20 25 30 35]


In [33]:
x[1:3]=15#Assigning 2 values with 15 indexed 1 and 2
print(x)

[ 5 15 15 20 25 30 35]


In [34]:
print(x[1:])

[15 15 20 25 30 35]


In [38]:
array_slice=x[2:5]

In [39]:
print(array_slice[:4])

[15 20 25]


In [40]:
array_slice[:3]=-1#Update to array_slice have update to original array x, better make copy of x--->x.copy()
x

array([ 5, 15, -1, -1, -1, 30, 35])

In [49]:
y = np.array([[0, 1, 2],
              [3, 4, 5]])
print(y[1:2, 1:3]) #In 1th row , select 1th column and 2nd column
print(y[1])   #Select 1th row
print(y[1,2])#select 1th row and 2nd colmn
print(y[:, 1]) #select all rows,and only 1th column

[[4 5]]
[3 4 5]
5
[1 4]


In [50]:
arr=np.arange(90).reshape(9,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [53]:
print(arr[1,1])#Its same as arr[1][1]
print(arr[1][1])

11
11


In [56]:
print(arr[1:7])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [55]:
print(arr[1:7,1:8])

[[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]
 [51 52 53 54 55 56 57]
 [61 62 63 64 65 66 67]]


In [88]:
z = np.array([
    [
        [1,2,3], 
        [1,2,3],
        [1,2,3]
    ],
    [
        [1,2,3],
        [1,10,10],
        [1,20,30]
    ],
    [
        [1,2,3],
        [1,40,50],
        [1,2,3]
    ]
])
# print(z.ndim,z.shape)
# print(z[1,:,1]) # index 1 element in row of index 1
print(z[1:,1:,:]) # From all outer rows except the first, select 1st index element (which itself is an array) completely.
# print(z[2]) # print 2nd index element

[[[ 1 10 10]
  [ 1 20 30]]

 [[ 1 40 50]
  [ 1  2  3]]]


for loop to iterate through numpy array

In [89]:
x = np.array([[-1, 1], [-2, 2]])
for row in x:
    print('Row :',row)

Row : [-1  1]
Row : [-2  2]


nditer method of numpy creates an iterator, which enable accessing each element one after the other.

In [93]:
import numpy as np
x = np.array([[0,1], [2, 3]])
for a in np.nditer(x):
    print(a)

0
1
2
3


Checking if every element of an array satisfies a condition, results in a Boolean array.
    This Boolean array can be used as index to filter elements that satisfy the condition.

In [92]:
x = np.arange(10).reshape(2,5)
print(x)
condition = x % 2 == 0
print(condition)
print(x[condition])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ True False  True False  True]
 [False  True False  True False]]
[0 2 4 6 8]


In [94]:
x = np.arange(12).reshape(3,4)
print(x[-2])

[4 5 6 7]


In [99]:

x = np.arange(30).reshape(3,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [100]:
print(x[1,::2,1])

[11 15 19]


In [101]:
print(x[1][::2][1])

[14 15]


In [102]:

x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [104]:
x=np.arange(30).reshape(6,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])