In [26]:
import numpy as np

Using zeros method

In [27]:
x = np.zeros(shape=(2,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Using full method

In [28]:
y = np.full(10,fill_value=10)
y

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [29]:
z=np.full(shape=(2,3),fill_value=10.5)
z

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

In [30]:
x = np.arange(3, 15, 2.5)#here 2.5 is  step i.e,3,3+2.5,3+2.5+2.5,...
x

array([ 3. ,  5.5,  8. , 10.5, 13. ])

In [31]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
y=np.linspace(3,10,5)
y

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [33]:
np.random.seed(100) # setting seed,seed will help us generate same set of random values on each execution
x = np.random.rand(2) # 2 random numbers between 0 and 1

print(x)

[0.54340494 0.27836939]


In [34]:
np.random.seed(100)
y=np.random.rand(10)#Dfault random values generated are btween 0 and 1
y

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [35]:
np.random.seed(100)
x=np.random.randint(10,20)#Generate random number between 10 and 20
x

18

In [36]:
np.random.seed(100)
x=np.random.randint(10,20,3)#Generate 3 random values between 10 and 20
x

array([18, 18, 13])

In [37]:
np.eye(4)#diagonal 1's and elswhere 0's

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.random.rand(3,2)#Generate random numbers between 0 and 1 with array of 3 rows and 2 columns

array([[0.4120464 , 0.52638247],
       [0.14860484, 0.15671108],
       [0.18646718, 0.21010774]])

In [39]:
np.random.random(3)#Generate 3 random numbers btn 0 and 1

array([0.4527399 , 0.87014264, 0.06368104])

In [40]:
import numpy as np

x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
#reset all exisitng numbers to 0's
print(y)

[[0 0 0]
 [0 0 0]]


In [41]:
np.ones(shape=(3,4))#Prints all array values as 1 depending one shape values

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

normal(loc=0.0, scale=1.0, size=None)
loc is mean , scale is standard deviation,size is number of elements
Draw random samples from a normal (Gaussian) distribution.

In [42]:
np.random.normal(loc=5,scale=2.5,size=5)

array([ 6.08204126, 10.76118148,  4.69341155,  5.03864828,  5.66504088])

In [43]:
np.random.seed(100)
x = np.random.randn(3) # Standard normal distribution
x

array([-1.74976547,  0.3426804 ,  1.1530358 ])

In [44]:
np.random.seed(100)
x = 10 + 2*np.random.randn(3) # normal distribution with mean 10 and sd 2

print(x)

[ 6.50046905 10.68536081 12.30607161]


In [45]:
np.random.seed(100)
np.random.normal(loc=10,scale=2.5,size=3)

array([ 5.62558632, 10.85670101, 12.88258951])

loadtxt is used to read data from a text file or any input data stream.

In [46]:
from io import StringIO

x = StringIO('''88.25 93.45 72.60 90.90
72.3 78.85 92.15 65.75
90.5 92.45 89.25 94.50
''')

d = np.loadtxt(x,delimiter=' ')
d

array([[88.25, 93.45, 72.6 , 90.9 ],
       [72.3 , 78.85, 92.15, 65.75],
       [90.5 , 92.45, 89.25, 94.5 ]])

In [47]:
print(d.ndim, d.shape)

2 (3, 4)


In [48]:

x = np.arange(4)
print(x.flatten())

[0 1 2 3]
