In [2]:
import numpy as np

1-d numpy array ndarrray

In [3]:
x = np.array([5,8,9,10,11]) 

In [4]:
x

array([ 5,  8,  9, 10, 11])

In [5]:
type(x)

numpy.ndarray

2-d numpy ndarray

In [6]:
y=np.array([[6,9,5],[10,82,34]])

In [7]:
y

array([[ 6,  9,  5],
       [10, 82, 34]])

In [8]:
type(y)

numpy.ndarray

numpy array attributes

In [9]:
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize, y.nbytes)

2 (2, 3) 6 int32 4 24


In [10]:
y.dtype

dtype('int32')

In [11]:
z = np.array([[6, 9, 5],[10, 82, 34]],dtype='float64') 

In [12]:
z.dtype

dtype('float64')

In [13]:
print(z)

[[ 6.  9.  5.]
 [10. 82. 34.]]


In [14]:
a = [
    [
        [4.1, 2.5], [1.1, 2.3], [9.1, 2.5]
    ], 
     [
         [8.6, 9.9],[3.6, 4.3], [6.6, 0.3]
     ]
]



In [15]:
x = np.array(a, dtype='float64')

In [16]:
x

array([[[4.1, 2.5],
        [1.1, 2.3],
        [9.1, 2.5]],

       [[8.6, 9.9],
        [3.6, 4.3],
        [6.6, 0.3]]])

In [17]:
type(x), x.ndim, x.shape

(numpy.ndarray, 3, (2, 3, 2))

Array Creation Methods
Numpy allows creation of arrays with default values like 0, 1, or another value