In [1]:
import numpy as np

In [2]:
np.random.seed(100)
x = np.random.randint(10, 100, 8)
print(x, end='\n\n')

[18 34 77 97 89 58 20 62]



In [3]:
y=x.reshape(2,4)
y

array([[18, 34, 77, 97],
       [89, 58, 20, 62]])

In [4]:
z=y.reshape(2,2,2)
z

array([[[18, 34],
        [77, 97]],

       [[89, 58],
        [20, 62]]])

In [5]:
x=np.array([[2,3],[4,5]])
y=np.array([[6,7],[8,9]])
np.vstack((x,y))#Vertically stacking arrays

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
x=np.arange(30).reshape(6,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])
np.hstack((x,y,z))#Horizontally stacking numpy arrays

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

In [8]:
np.vsplit(x,2)#Splitting naaray vertically into 2

[array([[-1,  1]]), array([[-3,  3]])]

In [9]:
x = np.arange(30).reshape(6, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [10]:
res = np.vsplit(x, (2, 5))#Splitting vertically at row2 and row5
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[25 26 27 28 29]]


In [11]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
res = np.hsplit(x, (2,4))#Splitting array horizontally at 2nd column and 4th column
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


In [13]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [14]:
y = np.arange(4, 8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [15]:
print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]
