In [1]:
import numpy as np

In [2]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
print(x + 10, end='\n\n')#Adds 10 to all elements of numpy array x

[[10 11 12]
 [13 14 15]]



In [4]:
print(x * 3, end='\n\n')#Multiplies 3 to all elements of numpy array x

[[ 0  3  6]
 [ 9 12 15]]



In [5]:
print(x % 2)#find reminder for all values of x

[[0 1 0]
 [1 0 1]]


In [6]:
#Operation between arrays happen element wise
x = np.array([[-1, 1], [-2, 2]])
y = np.array([[4, -4], [5, -5]])
print('array x')
print(x)
print('\n array y')
print(y)
print('\n Addition of x and y')
print(x + y, end='\n\n')
print('\n Multiplication of x and y')
print(x * y)

array x
[[-1  1]
 [-2  2]]

 array y
[[ 4 -4]
 [ 5 -5]]

 Addition of x and y
[[ 3 -3]
 [ 3 -3]]


 Multiplication of x and y
[[ -4  -4]
 [-10 -10]]


#Broadcasting numpy array
#operations of numpy arrays with varying size and shape

In [7]:
x = np.array([[-1, 1], [-2, 2]])
y = np.array([-10, 10])
print(x * y)

[[10 10]
 [20 20]]


In [21]:
#square of each element in numpy array
a=np.arange(1,11)
a=a**2
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
#perform operations on arrays with varying size and shape
#This is due Broadcasting feature exhibited by numpy arrays
x = np.array([[-1, 1], [-2, 2]])
y = np.array([-10, 10])
print(x * y)

[[10 10]
 [20 20]]


In [14]:
x = np.array([[0,1], [2,3]])
print(np.square(x), end='\n\n')
print(np.sin(x))

[[0 1]
 [4 9]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]


In [16]:
x = np.array([[0,1], [2, 3]])
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')#Verticalcolumn addition
print(x.sum(axis=1))#Horizontal row addition

6

[2 4]

[1 5]


In [22]:
np.sqrt(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
x = np.arange(20).reshape(4,5)
print(x)
print(x.mean(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 2.  7. 12. 17.]


In [25]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


In [26]:
x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]
